---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-bot
  namespace: qbittorrent-bot
spec:
  selector:
    matchLabels:
      app: qbittorrent-bot
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent-bot
    spec:
      containers:
      - name: qbittorrent-bot
        image: ch3p4ll3/qbittorrent-bot:latest
        command: ["/bin/bash","-c","--"]
        args: ["while true; do sleep 30; done;"]
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          subPath: config.json
        securityContext:
          runAsNonRoot: false
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
      - name: config-volume
        configMap: 
          name: config-json
